name: Trigger Internal Action
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Every hour, on the hour (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install lxml[html_clean]
          pip install -r requirements.txt

      - name: Run LLM Server # run main.py
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
            MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
            PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
            POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
            POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} 
            LLM_MODULE_HOST: ${{ secrets.LLM_MODULE_HOST }}
            LLM_MODULE_PORT: ${{ secrets.LLM_MODULE_PORT }}
            AUTOMATION_MODULE_URL: ${{ secrets.AUTOMATION_MODULE_URL }}
            FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        run: python src/llm/src/action.py 1
          
      - name: Pull changes
        run: git pull origin main
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 