name: Do Internal Action
on:
  workflow_dispatch:
  schedule:
    - cron: '30 17,23,2,5,8,11,14 * * *'  
    # “At minute 30 past hour 0, 6, 9, 12, 15, 18, and 21.”
    # This is set to be working to UTC+7 because github actions run by default in UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install dotenv

      - name: Execute cronjob script
        env:
            FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
            AUTOMATION_URL: ${{ secrets.AUTOMATION_URL }}
            LLM_URL: ${{ secrets.LLM_URL }}
        run: python cronjob/internal_action.py
          

####################################################
####################################################

#       - name: Pull changes
#         run: git pull origin main
          
#       - name: Commit files
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add -A
#           git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
#       - name: Push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: main 