name: Do Internal Action
# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 0,6,9,12,15,18,21 * * *' # “At minute 0 past hour 0, 6, 9, 12, 15, 18, and 21.”

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout repo content
#         uses: actions/checkout@v2 # checkout the repository content to github runner

#       - name: Setup python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10' # install the python version needed
          
#       - name: Install python packages
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Execute cronjob script
#         run: python cronjob/update_statistics.py
          

####################################################
####################################################

#       - name: Pull changes
#         run: git pull origin main
          
#       - name: Commit files
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add -A
#           git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
#       - name: Push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: main 